name: pymedx
channels:
  - nodefaults
  - conda-forge
dependencies:
  - compilers
  - python
  - pip
  - poetry >=2
  - nodejs # used by semantic-release
  - shellcheck
  - pip:
      - paginate
      - levenshtein==0.25.1  # pep517
